### PR TITLE
 Update check_env.py

### PR DESCRIPTION
**Pull request by scw**
An improved script which prints out the packages found and their versions in the success case for each. The current script has no output in a success case (all dependencies found).

### CODE REVIEW

**Comment by kastnerkyle** [comment]
This looks awesome! Thanks

**Comment by amueller** [comment]
@kastnerkyle have you tested it?

**Comment by kastnerkyle** [comment]
Working on that now :)

**Comment by amueller** [comment]
cool. lgtm from what I see

**Comment by kastnerkyle** [comment]
Works with a good environment - now checking a random subset of "FAIL" settings

**Comment by kastnerkyle** [comment]
One tiny fix... missing an f on first `from`

**Comment by kastnerkyle** [comment]
py2.6 doesn't have importlib. but that failure is already expected cause we want to reject anyways. I will merge this then fix the two tiny things

**Comment by amueller** [comment]
thanks @kastnerkyle and @scw

**Comment by scw** [comment]
Thanks for the additional fixes @kastnerkyle!

**Pull request merged**
