### PR TITLE
Add 'Pillow' to fix missing dependencies

### PR DESCRIPTION
**Pull request by bcbcarl**
`fetch_data.py` doesn't work without ~~`scikit-image`~~ `Pillow`.

### CODE REVIEW

**Comment by amueller** [comment]
Which part? there is no scikit-image import, right?

**Comment by bcbcarl** [comment]
`ImportError: The Python Imaging Library (PIL) is required to load data from jpeg files`

screen shot 2015-09-05 at 12 48 28 pm

**Comment by amueller** [comment]
ok. So you should add pillow, not scikit-image.

**Comment by bcbcarl** [comment]
Okay. I reverted all changes and added 'Pillow' to `check_env.py`.

**Comment by amueller** [comment]
Fixed in ba87a3ba6525e258e3c4980590f834e2fbac2a2f. Your version doesn't work, as PIL might be installed instead of Pillow. Your script failed on my box.

**Comment by amueller** [comment]
let me know if master works for you.

**Pull request closed without merging**
