### PR TITLE
added afternoon session rough plan

### PR DESCRIPTION
**Pull request by amueller**
More things for the afternoon. Do you think that is too much? I think it is now comparable to the last time. There is A LOT of time for all this. But I know I'm usually to fast ;)

### CODE REVIEW

**Comment by kastnerkyle** [comment]
I like the flow and don't think it is too much. For the out of core stuff it would be really nice to do an example using pytables and/or memmaps, I have personally been doing a lot with pytables lately and it would be nice to show how seamless it is.

And hashing trick is definitely good to show. Titanic might be too simple but it seemed like a more gripping "hello world" than iris or digits.

Streamlining the setup/how to get data part will be important but with that I think a solid 1+ hr of API and "core ML" followed by applications is a great way to go.

**Comment by amueller** [comment]
Ok so I'll merge this and we can built on it. I don't have pytables experience but it would be cool to show if you have a nice example.
I usually do use digits or iris to show of the interface of the classification examples, but I definitely want a dataset that has categorical variables, as that is something that people need to be aware of when using scikit-learn.

**Comment by kastnerkyle** [comment]
Agree 100%. I think iris and digits are good for the teaching part, but as
actual applications they pale compared to "who's probably gonna die in a
1900's shipwreck" ;)

**Comment by kastnerkyle** [comment]
Something with audio could be good too, but might to be too complex to set
up properly.

**Pull request merged**
